language: objective-c
osx_image: xcode10.3

before_install:
  - gem install cocoapods
  - cd example
  - pod install
  - cd ..

script:
  - xcodebuild test -workspace example/EzHTTPSample.xcworkspace/ -scheme EzHTTPSample -destination 'platform=iOS Simulator,name=iPhone 8'
  - pod lib lint  --allow-warnings

